### ISSUE TITLE
API link broken?

### ISSUE THREAD

**Issue by gjeanmart** [nieldlr/ethereum-gas-price-extension#10]
Hi, thanks for this super useful extension.

I noticed today the extension doesn't load gas prices anymore:

![image](https://user-images.githubusercontent.com/506784/86003629-fec4be00-ba09-11ea-92ea-93dbb496592e.png)

Maybe the EthGasStation API has somehow black listed the extension.

Thanks.

**Comment by gjeanmart** [comment]
Never mind, it's back :)

**Comment by gjeanmart** [comment]
Never mind, it's back :)

**Comment by nieldlr** [comment]
Sorry about this one @gjeanmart! I had to update the API call last week & there were some hiccups. Glad it's up & running!
